[package]
name = "nano-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
heapless = { workspace = true }
embedded-graphics = { workspace = true }
embedded-graphics-simulator = { workspace = true }

embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embassy-executor = { workspace = true }